Rancher Upgrade (#263)
Signed-off-by: Chandan Pinjani <chandan.pinjani@suse.com>

diff --git a/.github/workflows/master-e2e.yaml b/.github/workflows/master-e2e.yaml
--- a/.github/workflows/master-e2e.yaml
+++ b/.github/workflows/master-e2e.yaml
@@ -80,7 +80,6 @@ on:
         type: string
       rancher_version:
         description: Rancher Manager channel/version/head_version to use for installation
-        default: stable/latest/none
         type: string
       turtles_dev_chart:
         description: Install rancher turtles dev chart
@@ -101,7 +100,7 @@ on:
         required: false
         type: string
       upstream_cluster_version:
-        description: Cluster upstream version where to install Rancher (K3s or RKE2)
+        description: Cluster upstream version where to install Rancher (K3s)
         default: v1.31.4+k3s1
         type: string
       zone:
@@ -137,8 +136,8 @@ jobs:
         run: |
             if [[ "${{ inputs.grep_test_by_tag }}" =~ "@vsphere" ]]; then
               echo "initial-runner=vsphere" >> $GITHUB_OUTPUT
-              if [[ "${{ inputs.grep_test_by_tag }}" =~ "@full" || "${{ inputs.grep_test_by_tag }}" =~ "@short" ]]; then
-                echo "ERROR: @vsphere tests cannot be combined with @full and @short"
+              if [[ "${{ inputs.grep_test_by_tag }}" =~ "@full" || "${{ inputs.grep_test_by_tag }}" =~ "@short" || "${{ inputs.grep_test_by_tag }}" =~ "@upgrade" ]]; then
+                echo "ERROR: @vsphere tests cannot be combined with @full, @short and @upgrade"
                 exit 1
               fi
             else
@@ -289,25 +288,60 @@ jobs:
     needs: [create-runner, pre-qase]
     runs-on: ${{ needs.create-runner.outputs.uuid }}
     env:
-      CERT_MANAGER_VERSION: ${{ inputs.cert-manager_version }}
-      CLUSTER_NAME: ${{ inputs.cluster_name }}
-      CLUSTER_NS: fleet-default
-      # K3S / RKE2 flags to use for installation
+      # K3S flags to use for installation
       INSTALL_K3S_SKIP_ENABLE: true
       INSTALL_K3S_VERSION: ${{ inputs.upstream_cluster_version }}
       K3S_KUBECONFIG_MODE: 0644
-      # Distribution to use to host Rancher Manager (K3s or RKE2)
-      K8S_UPSTREAM_VERSION: ${{ inputs.upstream_cluster_version }}
       # For Rancher Manager
-      RANCHER_VERSION: ${{ inputs.rancher_version }}
-      TIMEOUT_SCALE: 3
+      RANCHER_USER: admin
+      RANCHER_URL: https://${{ needs.create-runner.outputs.public_dns }}/dashboard
+      CERT_MANAGER_VERSION: ${{ inputs.cert-manager_version }}
+      CLUSTER_NAME: ${{ inputs.cluster_name }}
+      # Qase
       QASE_API_TOKEN: ${{ secrets.qase_api_token }}
       QASE_PROJECT_CODE: RT
       QASE_RUN_ID: ${{ needs.pre-qase.outputs.qase_run_id }}
       # NOTE: this REPORT var is needed for Cypress!
       QASE_REPORT: 1
+      # Cypress
       TURTLES_REPO: rancher/turtles
       CONTROLLER_IMG: localhost:5000/$TURTLES_REPO
+      BROWSER: chrome
+      CYPRESS_DOCKER: 'cypress/included:14.5.0'
+      # Inputs
+      CAPI_UI_VERSION: ${{ inputs.capi_ui_version }}
+      GREPTAGS: ${{ inputs.grep_test_by_tag }}
+      TURTLES_CHART_VERSION: ${{ inputs.turtles_chart_version }}
+      SKIP_CLUSTER_DELETE: ${{ inputs.skip_cluster_delete }}
+      CLUSTER_NAME_SUFFIX: ${{ inputs.cluster_name_suffix }}
+      # Secrets
+      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
+      GCP_CREDENTIALS: ${{ secrets.gcp_credentials }}
+      GCP_PROJECT: ${{ secrets.gcp_project }}
+      AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
+      AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
+      AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}
+      AZURE_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}
+      VSPHERE_SECRETS_JSON_BASE64: ${{ secrets.vsphere_secrets_json_base64 }}
+      DOCKER_AUTH_USERNAME: ${{ secrets.docker_auth_username }}
+      DOCKER_AUTH_PASSWORD: ${{ secrets.docker_auth_password }}
+      DOCKER_REGISTRY_CONFIG: ${{ secrets.docker_registry_config }}
+      # Common specs: @short @vsphere @full
+      SPECS: |
+        e2e/capd_rke2_clusterclass.spec.ts
+        e2e/capd_rke2_fleet_clusterclass.spec.ts
+        e2e/capd_kubeadm_clusterclass.spec.ts
+        e2e/capd_kubeadm_ui_clusterclass.spec.ts
+        e2e/azure_rke2_v2prov_cluster.spec.ts
+        e2e/capv_rke2_clusterclass.spec.ts
+        e2e/capv_kubeadm_clusterclass.spec.ts
+        e2e/capa_rke2_clusterclass.spec.ts
+        e2e/capa_kubeadm_clusterclass.spec.ts
+        e2e/capg_kubeadm_clusterclass.spec.ts
+        e2e/capz_aks_clusterclass.spec.ts
+        e2e/capz_rke2_clusterclass.spec.ts
+        e2e/capz_kubeadm_clusterclass.spec.ts
     steps:
       - name: Add /usr/local/bin into PATH
         run: |
@@ -367,80 +401,51 @@ jobs:
           INDEX=$(((${{ github.run_number }} % 3) + 1))
           CP_ENDPOINT_IP=$(echo ${{ secrets.vsphere_endpoints_list }} | cut -d' ' -f${INDEX})
           sed -i "s/replace_cluster_control_plane_endpoint_ip/${CP_ENDPOINT_IP}/" tests/cypress/latest/fixtures/vsphere/capv-helm-values.yaml
+      - name: Set Rancher Manager Install version
+        run: |
+          if [[ "${{ inputs.grep_test_by_tag }}" =~ "@upgrade" ]]; then
+            # Required for upgrade tests
+            echo "RANCHER_VERSION=head/2.11" >> ${GITHUB_ENV}
+          else
+            echo "RANCHER_VERSION=${{ inputs.rancher_version }}" >> ${GITHUB_ENV}
+          fi
       - name: Install Rancher Manager
         env:
+          RANCHER_VERSION: ${{ env.RANCHER_VERSION }}
           PUBLIC_DNS: ${{ needs.create-runner.outputs.public_dns }}
         run: cd tests && make e2e-install-rancher
       - name: Extract component versions/information
         id: component
         run: |
-          # Extract CertManager version
-          CERT_MANAGER_VERSION=$(kubectl get pod \
+          # Extract CertManager image version
+          CERT_MANAGER_IMAGE_VERSION=$(kubectl get pod \
                                    --namespace cert-manager \
                                    -l app=cert-manager \
                                    -o jsonpath={.items[*].status.containerStatuses[*].image} 2> /dev/null || true)
-          # Extract Rancher Manager version
-          RM_VERSION=$(kubectl get pod \
+          # Extract Rancher Manager image version
+          RM_IMAGE_VERSION=$(kubectl get pod \
                          --namespace cattle-system \
                          -l app=rancher \
                          -o jsonpath={.items[*].status.containerStatuses[*].image} 2> /dev/null || true)
           # Export values
-          echo "cert_manager_version=${CERT_MANAGER_VERSION}" >> ${GITHUB_OUTPUT}
-          echo "rm_version=${RM_VERSION}" >> ${GITHUB_OUTPUT}
+          echo "cert_manager_image_version=${CERT_MANAGER_IMAGE_VERSION}" >> ${GITHUB_OUTPUT}
+          echo "rm_image_version=${RM_IMAGE_VERSION}" >> ${GITHUB_OUTPUT}
+          echo "rm_version=${{ env.RANCHER_VERSION }}" >> ${GITHUB_OUTPUT}
       - name: Install Chartmuseum
         if: ${{ inputs.turtles_dev_chart == true }}
         run: cd tests && make e2e-install-chartmuseum
       - name: Cypress tests
         env:
-          BROWSER: chrome
-          CYPRESS_DOCKER: 'cypress/included:14.5.0'
-          RANCHER_USER: admin
-          RANCHER_VERSION: ${{ steps.component.outputs.rm_version }}
-          RANCHER_URL: https://${{ needs.create-runner.outputs.public_dns }}/dashboard
-          QASE_RUN_ID: ${{ needs.pre-qase.outputs.qase_run_id }}
-          # Inputs
-          CAPI_UI_VERSION: ${{ inputs.capi_ui_version }}
-          K8S_UPSTREAM_VERSION: ${{ inputs.upstream_cluster_version }}
-          GREPTAGS: ${{ inputs.grep_test_by_tag }}
-          TURTLES_CHART_VERSION: ${{ inputs.turtles_chart_version }}
-          SKIP_CLUSTER_DELETE: ${{ inputs.skip_cluster_delete }}
-          CLUSTER_NAME_SUFFIX: ${{ inputs.cluster_name_suffix }}
-          # Secrets
+          RANCHER_VERSION: ${{ env.RANCHER_VERSION }}
           RANCHER_PASSWORD: ${{ secrets.rancher_password }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
-          GCP_CREDENTIALS: ${{ secrets.gcp_credentials }}
-          GCP_PROJECT: ${{ secrets.gcp_project }}
-          AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
-          AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
-          AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}
-          AZURE_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}
-          VSPHERE_SECRETS_JSON_BASE64: ${{ secrets.vsphere_secrets_json_base64 }}
-          DOCKER_AUTH_USERNAME: ${{ secrets.docker_auth_username }}
-          DOCKER_AUTH_PASSWORD: ${{ secrets.docker_auth_password }}
-          DOCKER_REGISTRY_CONFIG: ${{ secrets.docker_registry_config }}
           SPEC: |
             e2e/first_connection.spec.ts
             e2e/turtles_chart.spec.ts
             e2e/turtles_ui_extension.spec.ts
             e2e/menu.spec.ts
             e2e/providers_setup.spec.ts
+            ${{ env.SPECS }}
             e2e/capd_rke2_upgrade_clusterclass.spec.ts
-            e2e/capd_rke2_clusterclass.spec.ts
-            e2e/capd_rke2_fleet_clusterclass.spec.ts
-            e2e/capd_kubeadm_clusterclass.spec.ts
-            e2e/capd_kubeadm_ui_clusterclass.spec.ts
-            e2e/azure_rke2_v2prov_cluster.spec.ts
-            e2e/capv_rke2_clusterclass.spec.ts
-            e2e/capv_kubeadm_clusterclass.spec.ts
-            e2e/capa_rke2_clusterclass.spec.ts
-            e2e/capa_kubeadm_clusterclass.spec.ts
-            e2e/capg_kubeadm_clusterclass.spec.ts
-            e2e/capz_aks_clusterclass.spec.ts
-            e2e/capz_rke2_clusterclass.spec.ts
-            e2e/capz_kubeadm_clusterclass.spec.ts
-          UI_ACCOUNT: ${{ inputs.ui_account }}
-          UPGRADE_OS_CHANNEL: ${{ inputs.upgrade_os_channel }}
         run: |
           if ${{ inputs.qase_run_id == 'none' }}; then
             # Unset default QASE_* variables when reporting is disabled
@@ -453,20 +458,75 @@ jobs:
             export CHARTMUSEUM_REPO=http://${{ needs.create-runner.outputs.public_dns }}
           fi
           cd tests && make start-cypress-tests
-      - name: Upload Cypress screenshots (Basics)
+      - name: Upload Cypress screenshots
         if: failure() 
         uses: actions/upload-artifact@v4
         with:
-          name: cypress-screenshots-basics-${{ inputs.cluster_name }}
+          name: cypress-screenshots-${{ inputs.cluster_name }}
           path: tests/cypress/latest/screenshots
           retention-days: 7
           if-no-files-found: ignore
-      - name: Upload Cypress videos (Basics)
+      - name: Upload Cypress videos
         # Test run video is always captured, so this action uses "always()" condition
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: cypress-videos-basics-${{ inputs.cluster_name }}
+          name: cypress-videos-${{ inputs.cluster_name }}
+          path: tests/cypress/latest/videos
+          retention-days: 7
+      - name: Upgrade Rancher Manager
+        id: rancher_upgrade
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
+        env:
+          RANCHER_VERSION: head/2.12
+          PUBLIC_DNS: ${{ needs.create-runner.outputs.public_dns }}
+        run: cd tests && make e2e-upgrade-rancher
+      - name: Extract component versions/informations after Rancher Upgrade
+        id: upgraded_component
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
+        run: |
+          # Extract Rancher Manager image version
+          RM_UPGRADED_IMAGE_VERSION=$(kubectl get pod \
+            --namespace cattle-system \
+            -l app=rancher \
+            -o jsonpath={.items[*].status.containerStatuses[*].image} 2> /dev/null || true)
+          # Export values
+          echo "rm_upgraded_image_version=${RM_UPGRADED_IMAGE_VERSION}" >> ${GITHUB_OUTPUT}
+          echo "rm_upgraded_version=${{ env.RANCHER_VERSION }}" >> ${GITHUB_OUTPUT}
+      - name: Cypress tests - Upgraded Rancher
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
+        env:
+          RANCHER_VERSION: ${{ env.RANCHER_VERSION }}
+          RANCHER_PASSWORD: ${{ secrets.rancher_password }}
+          SPEC: |
+            e2e/capd_rke2_upgrade_clusterclass.spec.ts
+            ${{ env.SPECS }}
+        run: |
+          if ${{ inputs.qase_run_id == 'none' }}; then
+            # Unset default QASE_* variables when reporting is disabled
+            unset QASE_REPORT
+            unset QASE_API_TOKEN
+            # QASE_RUN_ID is empty string already
+          fi
+
+          if [ ${{ inputs.turtles_dev_chart }} == true ]; then
+            export CHARTMUSEUM_REPO=http://${{ needs.create-runner.outputs.public_dns }}
+          fi
+          cd tests && make start-cypress-tests
+      - name: Upload Cypress screenshots (after-upgrade)
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') && failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: cypress-screenshots-after-upgrade-${{ inputs.cluster_name }}
+          path: tests/cypress/latest/screenshots
+          retention-days: 7
+          if-no-files-found: ignore
+      - name: Upload Cypress videos (after-upgrade)
+        # Test run video is always captured, so this action uses "always()" condition
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') && always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: cypress-videos-after-upgrade-${{ inputs.cluster_name }}
           path: tests/cypress/latest/videos
           retention-days: 7
       - name: Add summary
@@ -475,17 +535,17 @@ jobs:
           # Add summary
           echo "## General informations" >> ${GITHUB_STEP_SUMMARY}
           echo -e "***${{ inputs.test_description }}***\n" >> ${GITHUB_STEP_SUMMARY}
-          echo "Type of cluster deployed: ${CLUSTER_TYPE:-normal}" >> ${GITHUB_STEP_SUMMARY}
-          echo "### Rancher Manager" >> ${GITHUB_STEP_SUMMARY}
-          echo "Rancher Manager Image: ${{ steps.component.outputs.rm_version }}" >> ${GITHUB_STEP_SUMMARY}
-          echo "Rancher Manager Version: ${{ inputs.rancher_version }}" >> ${GITHUB_STEP_SUMMARY}
-          echo "CertManager Image: ${{ steps.component.outputs.cert_manager_version }}" >> ${GITHUB_STEP_SUMMARY}
+          echo "### Rancher Manager & Turtles Information" >> ${GITHUB_STEP_SUMMARY}
+          echo "Rancher Manager Image: ${{ steps.component.outputs.rm_image_version }}" >> ${GITHUB_STEP_SUMMARY}
+          echo "Rancher Manager Version: ${{ steps.component.outputs.rm_version }}" >> ${GITHUB_STEP_SUMMARY}
+          echo "CertManager Image: ${{ steps.component.outputs.cert_manager_image_version }}" >> ${GITHUB_STEP_SUMMARY}
           UI_VERSION=$(helm list -n cattle-ui-plugin-system -o json 2> /dev/null |  jq -r '.[] | .chart')
           TURTLES_VERSION=$(helm list -n rancher-turtles-system -o json 2> /dev/null | jq -r '.[] | .chart')
           echo "CAPI UI Extension Version: $UI_VERSION" >> ${GITHUB_STEP_SUMMARY}
           echo "Rancher Turtles Installed/Upgraded Chart Version: $TURTLES_VERSION" >> ${GITHUB_STEP_SUMMARY}
-          if ${{ inputs.ui_account != '' }}; then
-            echo "UI User: ${{ inputs.ui_account }}" >> ${GITHUB_STEP_SUMMARY}
+          if [[ "${{ inputs.grep_test_by_tag }}" =~ "@upgrade" ]]; then
+            echo "### Rancher Manager Upgrade Information" >> ${GITHUB_STEP_SUMMARY}
+            echo "Rancher Manager Upgraded Image: ${{ steps.upgraded_component.outputs.rm_upgraded_image_version }}" >> ${GITHUB_STEP_SUMMARY}
           fi
           echo "### Kubernetes" >> ${GITHUB_STEP_SUMMARY}
           echo "K3s on Rancher Manager: ${{ env.INSTALL_K3S_VERSION }}" >> ${GITHUB_STEP_SUMMARY}
